### PR TITLE
[WIP] Various Changes

### LINKED ISSUE #36: Getting completion list for 'NvuiMoveScaler' crashes on Ubuntu
Platform: Ubuntu 20.04

Steps to Reproduce:
1. Open nvui
2. Type the command :NvuiMoveScaler<Space>
3. Press `<TAB>` to (if successful) get the completion list
4. nvui crashes from an exception.

The offending line is https://github.com/rohit-px2/nvui/blob/2bd38c0153ad09422b3bf1efc8788f181f4aba90/src/nvim.cpp#L479
which fails and throws 'std::bad_cast'.

This doesn't seem to happen on Windows.

### PR DESCRIPTION
**Pull request by rohit-px2**
- Fix crash on getting completion list (#36)
- Map Cmd key to C- key on Mac
- Add support for Super (D-) key
- Fix rendering issues on Mac (#70)
- Link `ext_cmdline` to default colors by default
- Fix alignment of popup menu info on `ext_multigrid` (workaround Neovim bug, can't be worked around without multigrid)
- Notify user of font families that couldn't be found

### CODE REVIEW

**Comment by bmulholland** [comment]
Segfaults on build:

```
% cmake --build build --target nvui --config Release -v
/usr/local/Cellar/cmake/3.21.3/bin/cmake -S/Users/bmulholland/sources/nvui -B/Users/bmulholland/sources/nvui/build --check-build-system CMakeFiles/Makefile.cmake 0
/Library/Developer/CommandLineTools/usr/bin/make  -f CMakeFiles/Makefile2 nvui
/usr/local/Cellar/cmake/3.21.3/bin/cmake -S/Users/bmulholland/sources/nvui -B/Users/bmulholland/sources/nvui/build --check-build-system CMakeFiles/Makefile.cmake 0
/usr/local/Cellar/cmake/3.21.3/bin/cmake -E cmake_progress_start /Users/bmulholland/sources/nvui/build/CMakeFiles 13
/Library/Developer/CommandLineTools/usr/bin/make  -f CMakeFiles/Makefile2 CMakeFiles/nvui.dir/all
/Library/Developer/CommandLineTools/usr/bin/make  -f CMakeFiles/nvui_autogen.dir/build.make CMakeFiles/nvui_autogen.dir/depend
cd /Users/bmulholland/sources/nvui/build && /usr/local/Cellar/cmake/3.21.3/bin/cmake -E cmake_depends "Unix Makefiles" /Users/bmulholland/sources/nvui /Users/bmulholland/sources/nvui /Users/bmulholland/sources/nvui/build /Users/bmulholland/sources/nvui/build /Users/bmulholland/sources/nvui/build/CMakeFiles/nvui_autogen.dir/DependInfo.cmake --color=
/Library/Developer/CommandLineTools/usr/bin/make  -f CMakeFiles/nvui_autogen.dir/build.make CMakeFiles/nvui_autogen.dir/build
[  7%] Automatic MOC and UIC for target nvui
/usr/local/Cellar/cmake/3.21.3/bin/cmake -E cmake_autogen /Users/bmulholland/sources/nvui/build/CMakeFiles/nvui_autogen.dir/AutogenInfo.json Release
[  7%] Built target nvui_autogen
/Library/Developer/CommandLineTools/usr/bin/make  -f CMakeFiles/nvui.dir/build.make CMakeFiles/nvui.dir/depend
cd /Users/bmulholland/sources/nvui/build && /usr/local/Cellar/cmake/3.21.3/bin/cmake -E cmake_depends "Unix Makefiles" /Users/bmulholland/sources/nvui /Users/bmulholland/sources/nvui /Users/bmulholland/sources/nvui/build /Users/bmulholland/sources/nvui/build /Users/bmulholland/sources/nvui/build/CMakeFiles/nvui.dir/DependInfo.cmake --color=
Dependencies file "CMakeFiles/nvui.dir/nvui_autogen/mocs_compilation.cpp.o.d" is newer than depends file "/Users/bmulholland/sources/nvui/build/CMakeFiles/nvui.dir/compiler_depend.internal".
Dependencies file "CMakeFiles/nvui.dir/src/cmdline.cpp.o.d" is newer than depends file "/Users/bmulholland/sources/nvui/build/CMakeFiles/nvui.dir/compiler_depend.internal".
Dependencies file "CMakeFiles/nvui.dir/src/cursor.cpp.o.d" is newer than depends file "/Users/bmulholland/sources/nvui/build/CMakeFiles/nvui.dir/compiler_depend.internal".
Dependencies file "CMakeFiles/nvui.dir/src/editor.cpp.o.d" is newer than depends file "/Users/bmulholland/sources/nvui/build/CMakeFiles/nvui.dir/compiler_depend.internal".
Dependencies file "CMakeFiles/nvui.dir/src/grid.cpp.o.d" is newer than depends file "/Users/bmulholland/sources/nvui/build/CMakeFiles/nvui.dir/compiler_depend.internal".
Consolidate compiler generated dependencies of target nvui
/Library/Developer/CommandLineTools/usr/bin/make  -f CMakeFiles/nvui.dir/build.make CMakeFiles/nvui.dir/build
[ 15%] Building CXX object CMakeFiles/nvui.dir/src/nvim.cpp.o
/Library/Developer/CommandLineTools/usr/bin/c++ -DBOOST_ALL_NO_LIB -DBOOST_FILESYSTEM_DYN_LINK -DBOOST_THREAD_DYN_LINK -DFMT_LOCALE -DFMT_SHARED -DQT_CORE_LIB -DQT_GUI_LIB -DQT_NO_DEBUG -DQT_SVG_LIB -DQT_WIDGETS_LIB -I/Users/bmulholland/sources/nvui/build -I/Users/bmulholland/sources/nvui -I/Users/bmulholland/sources/nvui/build/nvui_autogen/include -I/Users/bmulholland/sources/nvui/src -isystem /usr/local/include -iframework /usr/local/opt/qt5/lib -isystem /usr/local/opt/qt5/lib/QtCore.framework/Headers -isystem /usr/local/opt/qt5/./mkspecs/macx-clang -isystem /usr/local/opt/qt5/lib/QtGui.framework/Headers -isystem /Library/Developer/CommandLineTools/SDKs/MacOSX11.3.sdk/System/Library/Frameworks/OpenGL.framework/Headers -isystem /usr/local/opt/qt5/lib/QtWidgets.framework/Headers -isystem /usr/local/opt/qt5/lib/QtSvg.framework/Headers -O3 -DNDEBUG -O3 -DNDEBUG -flto=thin -isysroot /Library/Developer/CommandLineTools/SDKs/MacOSX11.3.sdk -Wall -Wextra -pedantic -Werror -Wfatal-errors -Wno-language-extension-token -fPIC -std=gnu++2a -MD -MT CMakeFiles/nvui.dir/src/nvim.cpp.o -MF CMakeFiles/nvui.dir/src/nvim.cpp.o.d -o CMakeFiles/nvui.dir/src/nvim.cpp.o -c /Users/bmulholland/sources/nvui/src/nvim.cpp
clang: fatal error: unable to execute command: Segmentation fault: 11
Apple clang version 13.0.0 (clang-1300.0.29.3)
Target: x86_64-apple-darwin20.6.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
make[3]: *** [CMakeFiles/nvui.dir/src/nvim.cpp.o] Error 254
make[2]: *** [CMakeFiles/nvui.dir/all] Error 2
make[1]: *** [CMakeFiles/nvui.dir/rule] Error 2
```

**Comment by rohit-px2** [comment]
I have no idea why that's happening but the mac actions are compiling fine. Maybe you could try the prebuilt distribution [here](https://github.com/rohit-px2/nvui/actions/runs/1262586379)?

**Comment by rohit-px2** [comment]
@bmulholland How is the branch working?

**Comment by bmulholland** [comment]
For reference, here's the same screenshot in a different GUI:

Screen Shot 2021-09-23 at 16 35 26

**Comment by rohit-px2** [comment]
Thanks for the help and screenshots!
It looks like the spacing issue is not completely fixed.

**Comment by bmulholland** [comment]
Thanks for working on it :)

**Pull request merged**
