### PR TITLE
Stricter compiler warning policy

### PR DESCRIPTION
**Pull request by mattfbacon**
Make warnings errors in `CMakeLists.txt`, and then fix all the resulting errors.

I was not able to fix the errors about unknown macros, but I'm not sure where they are coming from or what to do to fix it. Looks like it's related to cppcheck but you're not using cppcheck...

### CODE REVIEW

**Comment by rohit-px2** [comment]
Hey, thanks for doing this!
After you posted this I realized that builds weren't running for pull requests so I updated them to run on pull requests as well. Could you add an empty commit to trigger the build action? E.g. `git commit --allow-empty -m "Trigger build action"`

**Comment by mattfbacon** [comment]
(It requires your approval to run.)

**Comment by mattfbacon** [comment]
Looks like I missed some errors. Hmm, am I building it wrong? I just used CMake...

**Comment by mattfbacon** [comment]
FYI, looks like Windows Release action is broken. Something to do with installing Neovim via Chocolatey.

**Comment by rohit-px2** [comment]
I'll leave a PR on your branch to fix the Windows warnings when I have some time.

**Comment by mattfbacon** [comment]
I can soon if you don't. Next time I reboot ;)

**Comment by rohit-px2** [comment]
Alright everything looks good now, I'll merge it. Thanks for the help!

**Pull request merged**
